name: Update 3D Contribution Graph

on:
  schedule:
    - cron: '5 15 * * *'    # 매일 실행
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Generate 3D contribution SVGs
        uses: yoshi389111/github-profile-3d-contrib@main
        with:
          username: ${{ github.repository_owner }}
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Cache-bust README image query (robust)
        run: |
          ts=$(date -u +%Y%m%d%H%M%S)
          file="README.md"
          # profile-3d-contrib 폴더 안의 모든 .svg 링크에 ?t=타임스탬프 부착/교체
          sed -E -i "s#(profile-3d-contrib/[^\"')]+\.svg)(\?t=[0-9]+)?#\1?t=${ts}#g" "$file"

      - name: Commit & Push
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add -A
          git commit -m "chore: update 3D graph $ts" || echo "No changes"
          git push
