name: Update 3D Contribution Graph
on:
  schedule:
    - cron: '5 15 * * *'   # 매일 00:05 KST
  workflow_dispatch:

permissions:
  contents: write

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Generate 3D contribution SVGs
        uses: yoshi389111/github-profile-3d-contrib@0.9.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          USERNAME: ${{ github.repository_owner }}

      - name: Cache-bust README image query (robust)
        run: |
          ts=$(date -u +%Y%m%d%H%M%S)
          perl -0777 -pe "s#((?:\./)?(?:profile-3d-contrib|/profile-3d-contrib|https?://raw\.githubusercontent\.com/.+?/profile-3d-contrib)/[^\"'\)]+\.svg)(?:\?t=\d+)?#\1?t=${ts}#g" -i README.md
          grep -nE 'profile-3d-contrib/.+\.svg\?t=' README.md || true

      - name: Commit & Push
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add README.md profile-3d-contrib || true
          git commit -m "chore: cache-bust ($GITHUB_RUN_ID)" || echo "No changes"
          git push
